package com.duyi.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String scheduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_time
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private Date scheduleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.lan_type
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String lanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.price
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.room_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.room_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String roomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.film_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.film_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    private String filmName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_id
     *
     * @return the value of schedule.schedule_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_id
     *
     * @param scheduleId the value for schedule.schedule_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_time
     *
     * @return the value of schedule.schedule_time
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_time
     *
     * @param scheduleTime the value for schedule.schedule_time
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.lan_type
     *
     * @return the value of schedule.lan_type
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getLanType() {
        return lanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.lan_type
     *
     * @param lanType the value for schedule.lan_type
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setLanType(String lanType) {
        this.lanType = lanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.price
     *
     * @return the value of schedule.price
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.price
     *
     * @param price the value for schedule.price
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.room_id
     *
     * @return the value of schedule.room_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.room_id
     *
     * @param roomId the value for schedule.room_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.room_name
     *
     * @return the value of schedule.room_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.room_name
     *
     * @param roomName the value for schedule.room_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.film_id
     *
     * @return the value of schedule.film_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.film_id
     *
     * @param filmId the value for schedule.film_id
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.film_name
     *
     * @return the value of schedule.film_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.film_name
     *
     * @param filmName the value for schedule.film_name
     *
     * @mbg.generated Sun Sep 26 13:12:03 CST 2021
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName;
    }
}